{{- if .Values.podDisruptionBudget.enabled }}
{{- range $c := list "api" "worker" "web" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-%s" (include "nexus.fullname" $) $c }}
  labels:
    {{- include "nexus.labels" $ | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "nexus.selector" (list $ $c) | nindent 6 }}
{{- end }}
{{- end }}
