{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  selector:
    matchExpressions:
      - { key: app.kubernetes.io/instance, operator: In, values: [{{ .Release.Name }}] }
      - { key: app.kubernetes.io/component, operator: In, values: [api, worker] }
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      authorization:
        credentials: { name: {{ include "nexus.secretName" . }}, key: metricsToken }
{{- end }}
