{{- $name := printf "%s-web" (include "nexus.fullname" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels:
      {{- include "nexus.selector" (list . "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selector" (list . "web") | nindent 8 }}
        {{- with .Values.podLabels }}{{ toYaml . | nindent 8 }}{{ end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "nexus.spread" (list . "web") | nindent 6 }}
      containers:
        - name: web
          image: {{ include "nexus.image" (list .Values.image.web .) }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          env:
            - { name: NEXUS_API_URL, value: {{ printf "http://%s-api:8080" (include "nexus.fullname" .) | quote }} }
          ports:
            - { name: http, containerPort: 3100 }
          livenessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 5
            timeoutSeconds: 5
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
            - { name: next-cache, mountPath: /app/apps/web/.next/cache }
      volumes:
        - { name: tmp, emptyDir: {} }
        - { name: next-cache, emptyDir: {} }
      {{- with .Values.web.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "nexus.selector" (list . "web") | nindent 4 }}
  ports:
    - { name: http, port: 3100, targetPort: http }
