import type { ColumnType, Generated } from "kysely";

type Timestamp = ColumnType<Date, Date | string | undefined, Date | string>;
type NullableTimestamp = ColumnType<Date | null, Date | string | null | undefined, Date | string | null>;
type Json<T = Record<string, unknown>> = ColumnType<T, string | undefined, string>;

export type DevicePlatform = "macos" | "windows" | "linux";
export type Compliance = "compliant" | "non_compliant" | "unknown";
export type CheckStatus = "pass" | "fail" | "unknown" | "not_applicable";

export type SessionState = "pending_mfa" | "enroll_mfa" | "active";

export type UserStatus = "staged" | "active" | "suspended" | "deprovisioned";

export interface Database {
  organizations: {
    id: string;
    name: string;
    slug: string;
    settings: Json;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
    deletion_scheduled_for: Generated<Date | null>;
    deletion_requested_by: Generated<string | null>;
    deletion_requested_at: Generated<Date | null>;
    deletion_reason: Generated<string | null>;
  };
  users: {
    id: string;
    org_id: string;
    email: string;
    given_name: Generated<string>;
    family_name: Generated<string>;
    title: Generated<string>;
    department: Generated<string>;
    status: Generated<UserStatus>;
    password_hash: string | null;
    local_password_version: Generated<number>;
    local_password_fp: string | null;
    attributes: Json;
    break_glass: Generated<boolean>;
    last_login_at: NullableTimestamp;
    created_at: Generated<Date>;
    updated_at: Timestamp;
    manager_id: Generated<string | null>;
  };
  user_roles: {
    org_id: string;
    user_id: string;
    role: string;
    created_at: Generated<Date>;
  };
  groups: {
    id: string;
    org_id: string;
    name: string;
    description: Generated<string>;
    created_at: Generated<Date>;
    updated_at: Timestamp;
    rule: Json | null;
    rule_evaluated_at: NullableTimestamp;
  };
  group_members: {
    org_id: string;
    group_id: string;
    user_id: string;
    created_at: Generated<Date>;
  };
  sessions: {
    id: string;
    org_id: string;
    user_id: string;
    token_hash: Buffer;
    state: SessionState;
    client: string;
    ip: string;
    user_agent: string;
    mfa_at: NullableTimestamp;
    mfa_method: "totp" | "push" | "webauthn" | "recovery_code" | "idp" | null;
    created_at: Generated<Date>;
    last_seen_at: Timestamp;
    expires_at: Timestamp;
    revoked_at: NullableTimestamp;
    factor_id: ColumnType<string | null, string | null | undefined, string | null>;
    device_id: ColumnType<string | null, string | null | undefined, string | null>;
    device_verified_at: NullableTimestamp;
  };
  auth_factors: {
    id: string;
    org_id: string;
    user_id: string;
    type: "totp" | "push" | "webauthn";
    name: string;
    secret_sealed: Buffer | null;
    public_key: Buffer | null;
    verified_at: NullableTimestamp;
    last_used_at: NullableTimestamp;
    created_at: Generated<Date>;
    last_totp_step: number | null;
    credential_id: string | null;
    sign_count: Generated<number>;
    transports: Generated<string[]>;
  };
  auth_challenges: {
    id: string;
    org_id: string;
    user_id: string;
    purpose: "webauthn_register" | "webauthn_authenticate";
    challenge: string;
    created_at: Generated<Date>;
    expires_at: Timestamp;
  };
  invitations: {
    id: string;
    org_id: string;
    user_id: string;
    token_hash: Buffer;
    invited_by: string | null;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    accepted_at: NullableTimestamp;
    revoked_at: NullableTimestamp;
  };
  mfa_challenges: {
    id: string;
    org_id: string;
    user_id: string;
    session_id: string;
    number: number;
    choices: number[];
    status: Generated<"pending" | "approved" | "denied" | "expired">;
    context: Json;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    decided_at: NullableTimestamp;
    factor_id: ColumnType<string | null, string | null | undefined, string | null>;
    decision_reason: ColumnType<string | null, string | null | undefined, string | null>;
  };
  applications: {
    id: string;
    org_id: string;
    name: string;
    protocol: "oidc" | "saml";
    catalog_key: string | null;
    status: Generated<"active" | "disabled">;
    launch_url: Generated<string>;
    client_id: string | null;
    client_secret_hash: Buffer | null;
    redirect_uris: Generated<string[]>;
    config: Json;
    created_at: Generated<Date>;
    updated_at: Timestamp;
  };
  app_assignments: {
    org_id: string;
    app_id: string;
    principal_type: "user" | "group";
    principal_id: string;
    created_at: Generated<Date>;
  };
  signing_keys: {
    id: string;
    org_id: string;
    kid: string;
    alg: Generated<string>;
    public_jwk: Json;
    private_key_sealed: Buffer;
    status: Generated<"next" | "active" | "retired">;
    created_at: Generated<Date>;
    retired_at: NullableTimestamp;
    purpose: Generated<"oidc" | "saml">;
    cert_pem: string | null;
    not_after: NullableTimestamp;
  };
  oidc_codes: {
    id: string;
    org_id: string;
    code_hash: Buffer;
    app_id: string | null;
    mcp_client_id: Generated<string | null>;
    resource: Generated<string | null>;
    user_id: string;
    session_id: string | null;
    redirect_uri: string;
    scope: string;
    nonce: string | null;
    code_challenge: string | null;
    auth_time: Timestamp;
    amr: string[];
    created_at: Generated<Date>;
    expires_at: Timestamp;
    used_at: NullableTimestamp;
  };
  device_enrollment_tokens: {
    id: string;
    org_id: string;
    name: string;
    token_hash: Buffer;
    assign_user_id: string | null;
    created_by: string | null;
    max_uses: number | null;
    uses: Generated<number>;
    expires_at: Timestamp;
    revoked_at: NullableTimestamp;
    created_at: Generated<Date>;
  };
  devices: {
    id: string;
    org_id: string;
    hostname: string;
    platform: DevicePlatform;
    os_name: Generated<string>;
    os_version: Generated<string>;
    os_build: Generated<string>;
    arch: Generated<string>;
    model: Generated<string>;
    serial: Generated<string>;
    agent_version: Generated<string>;
    public_jwk: Json;
    key_thumbprint: string;
    primary_user_id: string | null;
    enrollment_token_id: string | null;
    status: Generated<"active" | "removed">;
    compliance: Generated<Compliance>;
    compliance_changed_at: NullableTimestamp;
    compliance_grace_until: NullableTimestamp;
    inventory: Json;
    posture: Json;
    osquery_version: string | null;
    enforcement_version: Generated<string>;
    enforcement_status: Generated<string>;
    settings_report: Json<unknown[]>;
    settings_reported_at: Generated<Date | null>;
    events_status: Generated<string>;
    osquery_collected_at: NullableTimestamp;
    enc_public_key: string | null;
    updates_checked_at: NullableTimestamp;
    updates_error: string | null;
    updates_pending: Generated<number>;
    security_updates_pending: Generated<number>;
    updates_pending_since: NullableTimestamp;
    security_updates_since: NullableTimestamp;
    third_party_pending: Generated<number>;
    third_party_since: NullableTimestamp;
    enrolled_at: Generated<Date>;
    last_seen_at: NullableTimestamp;
    last_ip: Generated<string>;
    created_at: Generated<Date>;
    updated_at: Timestamp;
  };
  device_checks: {
    org_id: string;
    device_id: string;
    check_key: string;
    status: CheckStatus;
    detail: string;
    updated_at: Timestamp;
    enforced: Generated<boolean>;
    failing_since: NullableTimestamp;
    grace_until: NullableTimestamp;
  };
  device_policies: {
    org_id: string;
    check_key: string;
    enabled: boolean;
    params: Json;
    mode: Generated<"audit" | "enforce">;
    grace_hours: Generated<number>;
    updated_at: Timestamp;
  };
  directory_service_settings: {
    org_id: string;
    ldap_enabled: Generated<boolean>;
    radius_enabled: Generated<boolean>;
    radius_mfa: Generated<"required" | "if_enrolled" | "off">;
    updated_at: Generated<Date>;
  };
  ldap_service_accounts: {
    id: string;
    org_id: string;
    name: string;
    secret_hash: string;
    created_by: string | null;
    created_at: Generated<Date>;
    last_used_at: Date | null;
    revoked_at: Date | null;
  };
  radius_clients: {
    id: string;
    org_id: string;
    name: string;
    address: string;
    secret: Buffer;
    created_by: string | null;
    created_at: Generated<Date>;
    last_used_at: Date | null;
    revoked_at: Date | null;
  };
  device_scripts: {
    id: string;
    org_id: string;
    name: string;
    description: Generated<string>;
    shell: "sh" | "bash" | "zsh" | "powershell";
    body: string;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  apple_mdm_settings: {
    org_id: string;
    ca_cert: string;
    ca_key: Buffer;
    push_key: Buffer | null;
    push_key_pending: Buffer | null;
    push_csr: string | null;
    push_cert: string | null;
    push_topic: string | null;
    push_expires_at: NullableTimestamp;
    updated_at: Generated<Date>;
  };
  apple_mdm_enroll_links: {
    id: string;
    org_id: string;
    name: string;
    token_hash: Buffer;
    uses: Generated<number>;
    created_by: string | null;
    created_at: Generated<Date>;
    expires_at: Date;
    revoked_at: NullableTimestamp;
  };
  apple_mdm_identities: {
    fingerprint: string;
    org_id: string;
    link_id: string | null;
    issued_at: Generated<Date>;
  };
  apple_mdm_devices: {
    id: string;
    org_id: string;
    udid: string;
    identity_fp: string;
    serial: Generated<string>;
    model: Generated<string>;
    device_name: Generated<string>;
    os_version: Generated<string>;
    topic: Generated<string>;
    push_token: string | null;
    push_magic: string | null;
    unlock_token: Buffer | null;
    bootstrap_token: Buffer | null;
    status: Generated<"authenticated" | "enrolled" | "checked_out">;
    device_id: string | null;
    info: Json<Record<string, unknown>>;
    security: Json<Record<string, unknown>>;
    enrolled_at: NullableTimestamp;
    last_seen_at: NullableTimestamp;
    created_at: Generated<Date>;
  };
  vault_accounts: {
    user_id: string;
    org_id: string;
    public_key: string;
    private_key_enc: Json<{ iv: string; ct: string }>;
    kdf: Json<{ alg: string; iterations: number; salt: string }>;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  vaults: {
    id: string;
    org_id: string;
    kind: "personal" | "shared";
    name_enc: Json<{ iv: string; ct: string }>;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  vault_members: {
    vault_id: string;
    user_id: string;
    org_id: string;
    wrapped_key: string;
    role: "owner" | "editor" | "viewer";
    added_by: string | null;
    created_at: Generated<Date>;
  };
  remote_assist_sessions: {
    id: string;
    org_id: string;
    device_id: string;
    requested_by: string | null;
    reason: string;
    status: Generated<"asking" | "active" | "declined" | "ended" | "expired" | "failed">;
    detail: Generated<string>;
    command_id: string | null;
    ticket_hash: string | null;
    ticket_expires_at: Date | null;
    created_at: Generated<Date>;
    accepted_at: Date | null;
    ended_at: Date | null;
    expires_at: Date;
  };
  vault_items: {
    id: string;
    org_id: string;
    vault_id: string;
    data: Json<{ iv: string; ct: string }>;
    created_by: string | null;
    updated_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  apple_ade_settings: {
    org_id: string;
    key: Buffer;
    cert: string;
    token: Buffer | null;
    token_expires_at: NullableTimestamp;
    server_name: Generated<string>;
    abm_org_name: Generated<string>;
    enroll_secret: string;
    profile_uuid: string | null;
    profile: Json<Record<string, unknown>>;
    auto_assign: Generated<boolean>;
    cursor: string | null;
    last_sync_at: NullableTimestamp;
    last_error: Generated<string>;
    updated_at: Generated<Date>;
  };
  apple_ade_devices: {
    org_id: string;
    serial: string;
    model: Generated<string>;
    description: Generated<string>;
    color: Generated<string>;
    os: Generated<string>;
    profile_status: Generated<string>;
    profile_uuid: Generated<string>;
    assigned_at: NullableTimestamp;
    deleted: Generated<boolean>;
    updated_at: Generated<Date>;
  };
  apple_mdm_profiles: {
    id: string;
    org_id: string;
    name: string;
    identifier: string;
    payload: Buffer;
    payload_types: Generated<string[]>;
    source: Generated<"upload" | "template">;
    target: Json<{ all?: boolean; group_ids?: string[] }>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  apple_mdm_device_profiles: {
    org_id: string;
    mdm_device_id: string;
    identifier: string;
    profile_id: string | null;
    status: "installing" | "installed" | "failed" | "removing";
    detail: Generated<string>;
    command_id: string | null;
    installed_version: NullableTimestamp;
    updated_at: Generated<Date>;
  };
  apple_mdm_commands: {
    id: string;
    org_id: string;
    mdm_device_id: string;
    request_type: string;
    command: Json<Record<string, unknown>>;
    status: Generated<"queued" | "sent" | "acknowledged" | "error" | "notnow" | "canceled">;
    result: Json<unknown> | null;
    error: Generated<string>;
    reason: Generated<string>;
    requested_by: string | null;
    created_at: Generated<Date>;
    sent_at: NullableTimestamp;
    finished_at: NullableTimestamp;
  };
  enforcement_exceptions: {
    org_id: string;
    rule_id: string;
    user_id: string;
    request_id: string | null;
    created_at: Generated<Date>;
  };
  device_accounts: {
    id: string;
    org_id: string;
    device_id: string;
    user_id: string;
    username: string;
    admin: Generated<boolean>;
    take_over: Generated<boolean>;
    status: Generated<"pending" | "waiting_password" | "active" | "disabled" | "failed">;
    password_version: Generated<number>;
    detail: Generated<string>;
    reported_at: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  password_deliveries: {
    org_id: string;
    device_id: string;
    user_id: string;
    version: number;
    ciphertext: string;
    created_at: Generated<Date>;
    expires_at: Date;
  };
  software_packages: {
    id: string;
    org_id: string;
    name: string;
    description: Generated<string>;
    platform: DevicePlatform;
    kind: "winget" | "msi" | "pkg" | "apt" | "dnf";
    ref: string;
    url: Generated<string>;
    sha256: Generated<string>;
    args: Json<string[]>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  software_assignments: {
    id: string;
    org_id: string;
    package_id: string;
    action: "install" | "remove";
    group_id: string | null;
    user_id: Generated<string | null>;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  device_software: {
    org_id: string;
    device_id: string;
    package_id: string;
    status: "installed" | "absent" | "failed" | "unsupported";
    detail: Generated<string>;
    updated_at: Generated<Date>;
  };
  patch_policies: {
    org_id: string;
    enabled: Generated<boolean>;
    scope: Generated<"security" | "all">;
    deadline_days: Generated<number>;
    restart: Generated<"never" | "if_needed">;
    window_start: Generated<number>;
    window_end: Generated<number>;
    third_party: Generated<boolean>;
    timezone: Generated<string>;
    updated_by: string | null;
    updated_at: Generated<Date>;
  };
  script_runs: {
    id: string;
    org_id: string;
    script_id: string | null;
    name: string;
    shell: string;
    body: string;
    body_sha256: string;
    reason: string;
    target: Json;
    device_count: number;
    requested_by: string | null;
    created_at: Generated<Date>;
    expires_at: Date;
  };
  mcp_clients: {
    id: string;
    org_id: string;
    client_id: string;
    name: string;
    redirect_uris: string[];
    created_at: Generated<Date>;
    last_used_at: Date | null;
  };
  mcp_grants: {
    id: string;
    org_id: string;
    user_id: string;
    client_id: string;
    resource: string;
    refresh_hash: Buffer;
    previous_hash: Buffer | null;
    created_at: Generated<Date>;
    last_used_at: Generated<Date>;
    expires_at: Date;
    revoked_at: Date | null;
  };
  mcp_dlp_policies: {
    org_id: string;
    arguments: Json;
    results: Json;
    custom: Json<unknown[]>;
    updated_at: Generated<Date>;
    updated_by: string | null;
  };
  browser_tokens: {
    id: string;
    org_id: string;
    name: string;
    token_hash: Buffer;
    created_by: string | null;
    created_at: Generated<Date>;
    last_used_at: Date | null;
    revoked_at: Date | null;
  };
  browser_policies: {
    org_id: string;
    apps: Json;
    dlp: Json;
    uploads: "allow" | "warn" | "block";
    message: string;
    saas_discovery: Generated<boolean>;
    updated_at: Generated<Date>;
    updated_by: string | null;
  };
  saas_usage: {
    org_id: string;
    app_key: string;
    user_email: string;
    user_id: string | null;
    day: string;
    visits: Generated<number>;
    password_logins: Generated<number>;
    blocked: Generated<number>;
    last_at: Date;
  };
  saas_apps: {
    org_id: string;
    app_key: string;
    status: "approved" | "unapproved";
    action: Generated<"allow" | "warn" | "block">;
    owner_id: string | null;
    notes: Generated<string>;
    updated_at: Generated<Date>;
    updated_by: string | null;
  };
  browser_events: {
    id: string;
    org_id: string;
    at: Date;
    received_at: Generated<Date>;
    user_email: string;
    user_id: string | null;
    kind: "visit" | "dlp" | "upload";
    action: "allowed" | "monitored" | "warned" | "continued" | "blocked";
    app: string;
    host: string;
    detector: string;
    count: number;
    detail: string;
    extension_version: string;
  };
  device_recovery_keys: {
    id: string;
    org_id: string;
    device_id: string;
    volume: string;
    key_id: string;
    sealed: Buffer;
    escrowed_at: Generated<Date>;
    retired_at: Date | null;
  };
  agent_nonces: {
    jti: string;
    org_id: string;
    device_id: string;
    expires_at: Timestamp;
  };
  access_policies: {
    id: string;
    org_id: string;
    name: string;
    enabled: Generated<boolean>;
    mode: Generated<"report_only" | "enforce">;
    requirement: "require_mfa" | "require_managed_device" | "require_compliant_device" | "block";
    conditions: Json;
    created_at: Generated<Date>;
    updated_at: Timestamp;
  };
  command_keys: {
    org_id: string;
    public_key: string;
    private_key: Buffer;
    created_at: Generated<Date>;
  };
  device_commands: {
    id: string;
    org_id: string;
    device_id: string;
    action: "refresh" | "lock" | "restart" | "wipe" | "osquery" | "script" | "updates" | "remote_assist";
    channel: "agent" | "mdm";
    status: Generated<"queued" | "sent" | "done" | "failed" | "expired" | "canceled">;
    reason: Generated<string>;
    output: Generated<string>;
    requested_by: string | null;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    sent_at: NullableTimestamp;
    finished_at: NullableTimestamp;
    args: Json;
    result: Json<unknown> | null;
    query_id: string | null;
    script_run_id: Generated<string | null>;
  };
  device_osquery: {
    org_id: string;
    device_id: string;
    name: string;
    rows: Json<Record<string, string>[]>;
    truncated: Generated<boolean>;
    error: Generated<string>;
    collected_at: Timestamp;
  };
  enforcement_rules: {
    id: string;
    org_id: string;
    name: string;
    kind: "app" | "domain";
    match: "name" | "path" | "sha256" | "domain";
    value: string;
    mode: Generated<"monitor" | "block">;
    target: Json<{ all?: boolean; group_ids?: string[] }>;
    platforms: Generated<string[]>;
    reason: Generated<string>;
    enabled: Generated<boolean>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  enforcement_events: {
    id: string;
    org_id: string;
    device_id: string;
    rule_id: string | null;
    rule_name: Generated<string>;
    action: "terminated" | "would_terminate" | "domain_blocked" | "failed";
    subject: Generated<string>;
    user_name: Generated<string>;
    count: Generated<number>;
    detail: Generated<string>;
    occurred_at: Timestamp;
    received_at: Generated<Date>;
  };
  device_process_events: {
    id: string;
    org_id: string;
    device_id: string;
    time: Timestamp;
    pid: Generated<number>;
    path: Generated<string>;
    cmdline: Generated<string>;
    user_name: Generated<string>;
    parent_path: Generated<string>;
    ancestors: Generated<string[]>;
    responsible_path: Generated<string>;
    signer: Generated<string>;
    detection: string | null;
    severity: "info" | "low" | "medium" | "high" | null;
    received_at: Generated<Date>;
  };
  risk_scores: {
    org_id: string;
    user_id: string;
    score: number;
    level: "low" | "medium" | "high" | "critical";
    factors: Json<unknown[]>;
    computed_at: Generated<Date>;
  };
  live_queries: {
    id: string;
    org_id: string;
    sql: string;
    reason: Generated<string>;
    target: Json;
    device_count: number;
    requested_by: string | null;
    created_at: Generated<Date>;
    expires_at: Timestamp;
  };
  access_reviews: {
    id: string;
    org_id: string;
    name: string;
    scope_type: "app" | "group" | "admin_roles";
    scope_id: string | null;
    reviewer_kind: "users" | "manager";
    reviewer_ids: Generated<string[]>;
    on_no_decision: Generated<"keep" | "revoke">;
    status: Generated<"open" | "closed">;
    due_at: Timestamp;
    reminded_at: NullableTimestamp;
    closed_at: NullableTimestamp;
    summary: Json;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  access_review_items: {
    id: string;
    org_id: string;
    review_id: string;
    user_id: string;
    grant_kind: "app_user" | "group_member" | "role";
    grant_ref: string;
    via: Generated<string>;
    reviewer_id: string | null;
    decision: "keep" | "revoke" | null;
    note: Generated<string>;
    decided_by: string | null;
    decided_at: NullableTimestamp;
    outcome: Generated<"" | "kept" | "revoked" | "already_gone" | "skipped">;
  };
  access_catalog: {
    id: string;
    org_id: string;
    resource_type: "app" | "group" | "role" | "block_exception" | "software";
    resource_id: string | null;
    role: string | null;
    description: Generated<string>;
    enabled: Generated<boolean>;
    max_hours: Generated<number>;
    allow_permanent: Generated<boolean>;
    stages: Json;
    eligible: Json;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  access_requests: {
    id: string;
    org_id: string;
    catalog_id: string;
    requester_id: string;
    justification: string;
    duration_hours: number | null;
    status: Generated<"pending" | "active" | "denied" | "canceled" | "ended" | "revoked">;
    stage: Generated<number>;
    auto_approved: Generated<boolean>;
    granted_at: NullableTimestamp;
    expires_at: NullableTimestamp;
    ended_at: NullableTimestamp;
    end_reason: Generated<string>;
    created_at: Generated<Date>;
  };
  access_decisions: {
    id: string;
    org_id: string;
    request_id: string;
    stage: number;
    approver_id: string | null;
    decision: "approve" | "deny";
    comment: Generated<string>;
    at: Generated<Date>;
  };
  mdm_connections: {
    id: string;
    org_id: string;
    provider: "intune" | "jamf";
    name: string;
    config: Json;
    secret: Buffer;
    enabled: Generated<boolean>;
    interval_minutes: Generated<number>;
    last_sync_at: NullableTimestamp;
    last_status: Generated<"never" | "ok" | "error">;
    last_error: Generated<string>;
    last_result: Json;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  mdm_devices: {
    org_id: string;
    connection_id: string;
    external_id: string;
    serial: Generated<string>;
    name: Generated<string>;
    platform: Generated<string>;
    os_version: Generated<string>;
    user_email: Generated<string>;
    managed: Generated<boolean>;
    compliant: boolean | null;
    compliance_detail: Generated<string>;
    encrypted: boolean | null;
    last_contact_at: NullableTimestamp;
    device_id: string | null;
    updated_at: Generated<Date>;
    management_id: Generated<string>;
  };
  identity_providers: {
    id: string;
    org_id: string;
    name: string;
    protocol: "oidc" | "saml";
    issuer: string | null;
    client_id: string | null;
    client_secret: Buffer | null;
    scopes: Generated<string>;
    idp_entity_id: string | null;
    idp_sso_url: string | null;
    idp_certs: Generated<string[]>;
    email_attribute: Generated<string>;
    domains: Generated<string[]>;
    jit_provisioning: Generated<boolean>;
    mfa: Generated<"when_signalled" | "always" | "never">;
    required: Generated<boolean>;
    enabled: Generated<boolean>;
    last_test_ok_at: NullableTimestamp;
    last_login_at: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  federated_identities: {
    id: string;
    org_id: string;
    idp_id: string;
    subject: string;
    user_id: string;
    created_at: Generated<Date>;
    last_login_at: NullableTimestamp;
  };
  federation_requests: {
    id: string;
    org_id: string;
    idp_id: string;
    purpose: "login" | "test";
    nonce: Generated<string>;
    code_verifier: Generated<string>;
    saml_request_id: Generated<string>;
    return_to: Generated<string>;
    client: Generated<string>;
    requested_by: string | null;
    result: Json | null;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    used_at: NullableTimestamp;
  };
  org_domains: {
    id: string;
    org_id: string;
    domain: string;
    token: string;
    status: Generated<"pending" | "verified" | "failing">;
    verified_at: NullableTimestamp;
    last_checked_at: NullableTimestamp;
    failing_since: NullableTimestamp;
    last_error: Generated<string>;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  notification_preferences: {
    user_id: string;
    org_id: string;
    email: Generated<"all" | "important" | "critical">;
    push: Generated<"all" | "important" | "critical">;
    timezone: Generated<string>;
    quiet_enabled: Generated<boolean>;
    quiet_start: Generated<string>;
    quiet_end: Generated<string>;
    digest_enabled: Generated<boolean>;
    digest_time: Generated<string>;
    updated_at: Generated<Date>;
  };
  org_alert_channels: {
    org_id: string;
    slack_webhook: Buffer | null;
    slack_min_severity: Generated<"info" | "warning" | "critical">;
    updated_at: Generated<Date>;
  };
  notification_deliveries: {
    id: string;
    org_id: string;
    notification_id: string | null;
    channel: "push" | "email" | "slack";
    status: "sent" | "failed" | "skipped" | "held";
    detail: Generated<string>;
    at: Generated<Date>;
  };
  recovery_codes: {
    id: string;
    org_id: string;
    user_id: string;
    code_hash: Buffer;
    used_at: NullableTimestamp;
    created_at: Generated<Date>;
  };
  password_resets: {
    id: string;
    org_id: string;
    user_id: string;
    token_hash: Buffer;
    ip: Generated<string>;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    used_at: NullableTimestamp;
  };
  event_destinations: {
    id: string;
    org_id: string;
    kind: "webhook" | "splunk_hec" | "datadog" | "s3" | "gcs" | "sentinel";
    name: string;
    url: string;
    secret: Buffer;
    config: Json;
    format: Generated<"nexus" | "ocsf">;
    event_filter: Generated<string[]>;
    enabled: Generated<boolean>;
    cursor_txid: string; // xid8, as text
    cursor_id: string;
    consecutive_failures: Generated<number>;
    next_attempt_at: Generated<Date>;
    last_error: Generated<string>;
    last_delivered_at: NullableTimestamp;
    disabled_reason: Generated<string>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  event_deliveries: {
    id: string;
    org_id: string;
    destination_id: string;
    at: Generated<Date>;
    ok: boolean;
    http_status: Generated<number>;
    events: Generated<number>;
    duration_ms: Generated<number>;
    error: Generated<string>;
  };
  api_keys: {
    id: string;
    org_id: string;
    name: string;
    prefix: string;
    key_hash: Buffer;
    scopes: string[];
    created_by: string | null;
    expires_at: Timestamp;
    last_used_at: NullableTimestamp;
    last_used_ip: Generated<string>;
    revoked_at: NullableTimestamp;
    created_at: Generated<Date>;
  };
  app_provisioning: {
    app_id: string;
    org_id: string;
    enabled: Generated<boolean>;
    base_url: string;
    token: Buffer;
    push_groups: Generated<boolean>;
    on_unassign: Generated<"deactivate" | "delete">;
    last_error: Generated<string>;
    last_error_at: NullableTimestamp;
    last_success_at: NullableTimestamp;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  provisioned_accounts: {
    org_id: string;
    app_id: string;
    user_id: string;
    remote_id: string | null;
    state: "active" | "inactive" | "error";
    attrs_hash: Generated<string>;
    last_error: Generated<string>;
    last_synced_at: Generated<Date>;
  };
  provisioned_groups: {
    org_id: string;
    app_id: string;
    group_id: string;
    remote_id: string;
    display_name: string;
    last_synced_at: Generated<Date>;
  };
  directory_connections: {
    id: string;
    org_id: string;
    provider: "google" | "entra" | "scim" | "ldap" | "bamboohr" | "workday";
    name: string;
    config: Json;
    secret: Buffer | null;
    enabled: Generated<boolean>;
    sync_groups: Generated<boolean>;
    group_filter: Generated<string[]>;
    deprovision: Generated<"suspend" | "offboard" | "none">;
    invite_new_users: Generated<boolean>;
    interval_minutes: Generated<number>;
    last_sync_at: NullableTimestamp;
    last_status: Generated<"never" | "ok" | "error" | "needs_approval">;
    last_result: Json;
    last_error: Generated<string>;
    token_hash: Buffer | null;
    token_hint: Generated<string>;
    last_request_at: NullableTimestamp;
    deactivations_allowed_until: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  ai_agents: {
    id: string;
    org_id: string;
    name: string;
    description: Generated<string>;
    owner_user_id: string | null;
    owner_group_id: string | null;
    environment: Generated<"production" | "staging" | "development">;
    runtime: Generated<string>;
    model: Generated<string>;
    risk_tier: Generated<"low" | "medium" | "high" | "critical">;
    tags: Generated<string[]>;
    client_id: string;
    status: Generated<"active" | "suspended">;
    status_reason: Generated<string>;
    token_ttl_minutes: Generated<number>;
    tokens_valid_after: Generated<Date>;
    last_token_at: NullableTimestamp;
    last_seen_at: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  agent_credentials: {
    id: string;
    org_id: string;
    agent_id: string;
    kind: "secret" | "public_key" | "federated";
    name: Generated<string>;
    secret_hash: string | null;
    hint: Generated<string>;
    public_jwk: Json | null;
    key_id: string | null;
    fed_issuer: string | null;
    fed_subject: string | null;
    fed_audience: string | null;
    expires_at: NullableTimestamp;
    last_used_at: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
    revoked_at: NullableTimestamp;
  };
  agent_assertion_jtis: {
    org_id: string;
    jti: string;
    expires_at: Date;
  };
  mcp_servers: {
    id: string;
    org_id: string;
    name: string;
    slug: string;
    description: Generated<string>;
    url: string;
    auth_kind: Generated<"none" | "bearer" | "header">;
    auth_header: Generated<string>;
    secret: Buffer | null;
    status: Generated<"active" | "disabled">;
    auto_approve_read: Generated<boolean>;
    calls_per_minute: Generated<number>;
    server_info: Json;
    last_synced_at: NullableTimestamp;
    last_sync_error: Generated<string>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  mcp_tools: {
    id: string;
    org_id: string;
    server_id: string;
    name: string;
    title: Generated<string>;
    description: Generated<string>;
    input_schema: Json;
    annotations: Json;
    hash: string;
    status: Generated<"pending" | "approved" | "blocked" | "removed">;
    change: Generated<"new" | "changed" | "">;
    approved_hash: string | null;
    approved_snapshot: Json | null;
    approved_by: string | null;
    approved_at: NullableTimestamp;
    risk: "read" | "write" | "external" | "destructive";
    risk_source: Generated<"heuristic" | "annotations" | "admin">;
    first_seen_at: Generated<Date>;
    changed_at: Generated<Date>;
  };
  mcp_permissions: {
    id: string;
    org_id: string;
    server_id: string;
    effect: "allow" | "deny";
    subject_type: "all_agents" | "agent" | "agent_tag" | "all_people" | "user" | "group";
    subject_id: string | null;
    subject_tag: string | null;
    tools: string[];
    risks: string[] | null;
    conditions: Json;
    description: Generated<string>;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  audit_blocks: {
    org_id: string;
    seq: ColumnType<string, number | string, never>; // bigint
    from_txid: string; // xid8, as text
    from_id: string;
    to_txid: string;
    to_id: string;
    count: number;
    first_ts: Date;
    last_ts: Date;
    prev_digest: string;
    digest: string;
    sealed_at: Generated<Date>;
    pruned_at: NullableTimestamp;
  };
  alert_rules: {
    id: string;
    org_id: string;
    builtin_key: string | null;
    name: string;
    description: Generated<string>;
    enabled: Generated<boolean>;
    severity: "low" | "medium" | "high" | "critical";
    match: Json;
    group_by: Generated<"none" | "actor" | "target" | "ip">;
    threshold: Generated<number>;
    window_minutes: Generated<number>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  alert_cursors: {
    org_id: string;
    cursor_txid: string;
    cursor_id: string;
  };
  alert_hits: {
    org_id: string;
    rule_id: string;
    group_key: string;
    event_id: string;
    at: Date;
  };
  alerts: {
    id: string;
    org_id: string;
    rule_id: string | null;
    rule_name: string;
    group_key: string;
    subject: Generated<string>;
    title: string;
    severity: "low" | "medium" | "high" | "critical";
    status: Generated<"open" | "acknowledged" | "resolved">;
    count: Generated<number>;
    event_ids: Generated<string[]>;
    first_seen_at: Date;
    last_seen_at: Date;
    assignee_id: string | null;
    snoozed_until: NullableTimestamp;
    acknowledged_by: Generated<string>;
    acknowledged_at: NullableTimestamp;
    resolved_by: Generated<string>;
    resolved_at: NullableTimestamp;
    resolution: Generated<"" | "true_positive" | "false_positive" | "benign">;
    paged: Json<string[]>;
    created_at: Generated<Date>;
  };
  alert_notes: {
    id: string;
    org_id: string;
    alert_id: string;
    author_id: string | null;
    author: string;
    body: string;
    at: Generated<Date>;
  };
  oncall_integrations: {
    id: string;
    org_id: string;
    kind: "pagerduty" | "opsgenie";
    name: string;
    secret: Buffer;
    region: Generated<"us" | "eu">;
    min_severity: Generated<"low" | "medium" | "high" | "critical">;
    enabled: Generated<boolean>;
    inbound_hash: string;
    last_error: Generated<string>;
    last_sent_at: NullableTimestamp;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  custom_roles: {
    id: string;
    org_id: string;
    name: string;
    description: Generated<string>;
    permissions: string[];
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  role_grants: {
    id: string;
    org_id: string;
    user_id: string;
    builtin_role: "helpdesk" | "security_analyst" | "readonly" | null;
    custom_role_id: string | null;
    scope_group_ids: Generated<string[]>;
    created_by: string | null;
    created_at: Generated<Date>;
  };
  directory_links: {
    org_id: string;
    connection_id: string;
    kind: "user" | "group";
    external_id: string;
    local_id: string;
    suspended_by_sync: Generated<boolean>;
  };
  jobs: {
    id: string;
    org_id: string;
    kind: string;
    payload: Json;
    status: Generated<"queued" | "running" | "done" | "dead">;
    run_at: Timestamp;
    attempts: Generated<number>;
    max_attempts: Generated<number>;
    locked_until: NullableTimestamp;
    last_error: Generated<string>;
    dedupe_key: string | null;
    created_at: Generated<Date>;
    finished_at: NullableTimestamp;
  };
  agent_update_settings: {
    org_id: string;
    auto_rollout: Generated<boolean>;
    advance_after_hours: Generated<number>;
    updated_at: Generated<Date>;
  };
  agent_rollouts: {
    id: string;
    org_id: string;
    version: string;
    stage: Generated<"canary" | "early" | "all">;
    status: Generated<"active" | "paused" | "halted" | "completed" | "cancelled">;
    canary_device_ids: Generated<string[]>;
    stage_started_at: Generated<Date>;
    failures_since: Generated<Date>;
    halted_reason: Generated<string>;
    created_by: string | null;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
  };
  device_updates: {
    org_id: string;
    device_id: string;
    version: string;
    state: "offered" | "installed" | "failed" | "rolled_back";
    error: Generated<string>;
    from_version: Generated<string>;
    updated_at: Generated<Date>;
  };
  device_trust_challenges: {
    id: string;
    org_id: string;
    session_id: string;
    nonce: string;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    used_at: NullableTimestamp;
  };
  device_pairings: {
    id: string;
    org_id: string;
    user_id: string;
    session_id: string | null;
    code_hash: Buffer;
    created_at: Generated<Date>;
    expires_at: Timestamp;
    used_at: NullableTimestamp;
  };
  push_registrations: {
    id: string;
    org_id: string;
    user_id: string;
    factor_id: string | null;
    platform: "ios" | "android" | "web";
    token: string;
    created_at: Generated<Date>;
    last_seen_at: Timestamp;
  };
  audit_events: {
    id: string;
    org_id: string;
    ts: Generated<Date>;
    type: string;
    outcome: "success" | "failure" | "denied";
    actor_type: string;
    actor_id: string | null;
    actor_display: string;
    target_type: string;
    target_id: string | null;
    target_display: string;
    session_id: string | null;
    ip: string;
    user_agent: string;
    details: Json;
  };
  notifications: {
    id: string;
    org_id: string;
    recipient_user_id: string;
    category: string;
    severity: "info" | "warning" | "critical";
    title: string;
    body: string;
    entity_type: string;
    entity_id: string | null;
    link: string;
    actions: Json<NotificationAction[]>;
    created_at: Generated<Date>;
    read_at: NullableTimestamp;
    archived_at: NullableTimestamp;
    acted_at: NullableTimestamp;
  };
}

export type NotificationAction = { id: string; label: string; style?: "primary" | "danger" };
